management:
  security:
    enabled: true
---    
security:
  user:
    name: admin
    password: admin    
    
---    

#Ribbon config
demoApp:
  ribbon:
    ConnectionTimeout: 300000
    DeploymentContextBasedVipAddress: demoApp
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    ReadTimeout: 300000
    ServerListRefreshInterval: 6000
 