security:
  user:
    name: admin
    password: admin
  basic:
    enabled: false 
management:
  security:
    enabled: false
    
jwt.secret.key: abc$$123$      

public.urls: /env,/health,/metrics,/info,/refresh


          