security:
  user:
    name: admin
    password: admin
  basic:
    enabled: false 
management:
  security:
    enabled: false
    
jwt.secret.key: abc$$123$      
    
endpoints:
  metrics:
    sensitive: true
    enabled: true
  health:
    sensitive: true
    enabled: true
  enabled: false           