spring:
  datasource:
    username: venkat
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@localhost:1521/xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: venkat 
    hikari:
      pool-name: DemoHikariPool
      
---      
      
logging:
  level:
    com.demo: DEBUG      
      
      